[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capstone = "SubsfvX3BEXk4JpzwFXUAL5H51rZtyooPSTprzjGeTz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/capstone.ts\""
devnet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/devnet-demo.ts\""
create-subscription = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/demo/createSubscription.ts\""
subscribe = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/demo/subscribe.ts\""
cancel-subscription = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/demo/cancelSubscription.ts\""
close-vault = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/demo/closeVault.ts\""
